name: Despliegue Produccion Interbank

on:
  push:
    branches:
      - main

# Declarar los permisos necesarios para que el workflow reutilizable pueda ejecutarlos
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  Llamar-Pipeline-Corporativo:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      app_name: 'interbank-app-18699'
    secrets:
      PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}