name: Estandar Reusable DevSecOps

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      PUBLISH_PROFILE:
        required: true

jobs:
  Build-And-Scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript'
          # Indicarle a CodeQL que no intente compilar automáticamente si no hay un build system complejo
          build-mode: 'none'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Empaquetar Artefacto
        run: zip -r app.zip .

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: webapp-artifact
          path: app.zip

  Deploy-To-Azure:
    needs: Build-And-Scan
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Artefacto
        uses: actions/download-artifact@v4
        with:
          name: webapp-artifact

      - name: Despliegue en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app_name }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}